local_costmap:
   global_frame: $(arg robot_name)_tf/odom
   robot_base_frame: $(arg robot_name)_tf/base_footprint
   update_frequency: 4.0
   publish_frequency: 1.0
#   static_map: true
   rolling_window: true
   width: 2.0
   height: 2.0
   resolution: 0.02
   transform_tolerance: 0.5
   plugins:
      - { name: obstacle_layer,      type: "costmap_2d::ObstacleLayer" }
      - { name: inflation_layer,     type: "costmap_2d::InflationLayer" }
