# Path of the agent launch file
agent_launch_file: '/home/antrobot/catkin_ws/src/costmap_merge/launch/includes/agent.launch'

robot_names: ['robot3', 'robot4']       # names of all the robots in the fleet
robot_type: 'robin50'                   # Type of robot
coordinates: [3, 3, 0, 0, 0, 0]         # Robot starting position
can_detect: True                        # is capable of detecting other robots
