# Path of the agent launch file
agent_launch_file: '/home/antrobot/catkin_ws/src/costmap_merge/launch/agent.launch'

robots:
  robot3:
    robot_type: 'robin50'                   # Type of robot
    coordinates: [ 3, 2, 0, 0, 0, 0 ]         # Robot starting position
    can_detect: True                        # is capable of detecting other robots
  robot4:
    robot_type: 'robin50'                   # Type of robot
    coordinates: [3, -2, 0, 0, 0, 0]         # Robot starting position
    can_detect: True                        # is capable of detecting other robots
