                            ############################
                            # Real Launcher Parameters #
                            ############################

###################################################################################
# Path of the agent launch file
agent_launch_file: '/home/antrobot/catkin_ws/src/costmap_merge/launch/agent.launch'
detector_file: 'pc_detector.py'
listener_file: 'pc_listener.py'

#####################################################
# The parameter 'mode' enables 2 modes of operation #
#   - Independent frames                            #
#   - Common frame (using coordinates values)       #
#####################################################

robots:
  robot1:
    robot_type: 'robin50'                   # Type of robot
    coordinates: [0, 0, 0, 0, 0, 0]         # Robot starting position
    can_detect: True                        # is capable of detecting other robots
    tag_id: '0001'                          # RFID tag ID
  robot2:
    robot_type: 'robin50'                   # Type of robot
    coordinates: [0, 0, 0, 0, 0, 0]         # Robot starting position
    can_detect: True                        # is capable of detecting other robots
    tag_id: '0002'                          # RFID tag ID
  robot3:
    robot_type: 'robin50'                   # Type of robot
    coordinates: [2, 0, 0, 0, 0, 1.57]      # Robot starting position
    can_detect: True                        # is capable of detecting other robots
    tag_id: '0003'                          # RFID tag ID
  robot4:
    robot_type: 'robin50'                   # Type of robot
    coordinates: [0, 0, 0, 0, 0, 0]         # Robot starting position
    can_detect: True                        # is capable of detecting other robots
    tag_id: '0004'                          # RFID tag ID
  robot5:
    robot_type: 'robin50'                   # Type of robot
    coordinates: [0, 0, 0, 0, 0, 0]         # Robot starting position
    can_detect: True                        # is capable of detecting other robots
    tag_id: '0005'                          # RFID tag ID
