##############################################################################
# Robot Launcher Parameters
##############################################################################

########################## global config vars ################################

robot_types: ['robin50', 'quadrotor', 'turtlebot']
num_robots: [1, 0, 0]

detector_file: 'detector.py'
listener_file: 'listener.py'

##############################################################################

# Set random configuration. If False the fixed robot poses and/or costmap sizes are used.
random_pose: False
random_costmap_dimensions: False

# Robot parameters
# robot_name = robot_type-robot_num
quadrotor_1:
  coordinates: [ 0, -3, 2, 0, 0, 3.14 ]  # x, y, z, roll, pitch, yaw
  costmap: [ 3, 3 ]  # width, height
  can_detect: True
quadrotor_2:
  coordinates: [ 1, -3, 2, 0, 0, 3.14 ]  # x, y, z, roll, pitch, yaw
  costmap: [ 3, 3 ]  # width, height
  can_detect: True
robin50_1:
  coordinates: [1, -2, 0, 0, 0, 1.57]
  costmap: [3, 3]
  can_detect: True
robin50_2:
  coordinates: [-1, -2, 0, 0, 0, 0]
  costmap: [3, 3]
  can_detect: True
robin50_3:
  coordinates: [-3, -6, 0, 0, 0, 0]
  costmap: [3, 3]
  can_detect: True
turtlebot_1:
  coordinates: [0, -2, 0, 0, 0, -1]
  costmap: [3, 3]
  can_detect: True
turtlebot_2:
  coordinates: [-3, -3, 0, 0, 0, 0.5]
  costmap: [3, 3]
  can_detect: True
turtlebot_3:
  coordinates: [ -6, -3, 0, 0, 0, 0 ]
  costmap: [ 3, 3 ]
  can_detect: True

# More costmap parameters
costmap_resolution: 0.05