##############################################################################
# Robot Launcher Parameters
##############################################################################

########################## .launch file paths ################################
# turtlebot2:
robot_launch_file: '/home/sergi/catkin_ws/src/costmap_merge/launch/includes/robot.launch'

##############################################################################

# number of robots. If fixed poses and costmaps are used, don't exceed the number of configuration per robot type.
num_detectors: 2
num_robots: 1

# Set random configuration. If False the fixed robot poses and/or costmap sizes are used.
random_pose: False
random_costmap_dimensions: False

# Fixed Robot positions and costmap sizes
detector1:
  coordinates: [3, -3, 0, 0, 0, 3.14]  # x, y, z, roll, pitch, yaw
  costmap: [3, 3]  # width, height
detector2:
  coordinates: [-3, -3, 0, 0, 0, 0]  # x, y, z, roll, pitch, yaw
  costmap: [3, 3]
robot1:
  coordinates: [0, -2, 0, 0, 0, -1.57]
  costmap: [3, 3]
robot2:
  coordinates: [-3, -3, 0, 0, 0, 0]
  costmap: [3, 3]

# More costmap parameters
costmap_resolution: 0.05