##############################################################################
# Robot Launcher Parameters
##############################################################################

# File names
detector_launch_file: '/home/sergi/catkin_ws/src/costmap_merge/launch/includes/detector.launch'
robot_launch_file: '/home/sergi/catkin_ws/src/costmap_merge/launch/includes/robot.launch'

# number of robots
num_detectors: 1
num_robots: 2

# Fixed Robot positions
d1: [0, 0, 0, 0, 0, 1.57]
r1: [-3, 0, 0, 0, 0, -1.57]
r2: [3, 0, 0, 0, 0, 3.14]
