global_costmap:
   global_frame: world
   robot_base_frame: base_footprint
   update_frequency: 0.1
   publish_frequency: 0.1
   transform_tolerance: 0.5
#   static_map: false
   rolling_window: true
   width: 50
   height: 50
   resolution: $(arg resolution)
   plugins:
#      - { name: static_layer,        type: "costmap_2d::StaticLayer" }
      - { name: obstacle_layer,      type: "costmap_2d::ObstacleLayer" }
      - { name: inflation_layer,     type: "costmap_2d::InflationLayer" }


