local_costmap:
   global_frame: $(arg tf_prefix)/world
   robot_base_frame: $(arg tf_prefix)/base_footprint
   update_frequency: 4.0
   publish_frequency: 1.0
#   static_map: true
   rolling_window: true
   width: $(arg width)
   height: $(arg height)
   resolution: $(arg resolution)
   transform_tolerance: 0.5
   plugins:
      - { name: obstacle_layer,      type: "costmap_2d::ObstacleLayer" }
      - { name: inflation_layer,     type: "costmap_2d::InflationLayer" }
