max_obstacle_height: 1.60  # assume something like an arm is mounted on top of the robot

# Obstacle Cost Shaping (http://wiki.ros.org/costmap_2d/hydro/inflation)
robot_radius: 0.20  # distance a circular robot should be clear of the obstacle (kobuki: 0.18)
footprint_padding: 0.00

# map_type: voxel
always_send_full_costmap: true

obstacle_layer:
  enabled:              true
  track_unknown_space:  false    #true needed for disabling global path planning through unknown space
  combination_method: 1
  observation_sources: scan # ["scan","bump"]
  scan:
    sensor_frame: $(arg tf_prefix)/camera_depth_frame
    data_type: LaserScan
    topic: scan
    observation_persistence: 0
    marking: true
    clearing: true
    obstacle_range: 3.5
    raytrace_range: 3.5
    min_obstacle_height: 0.1 # 0.25
    max_obstacle_height: 0.4 # 0.35
    inf_is_valid: true
#  bump:
#    sensor_frame: $(arg tf_prefix)_tf/base_footprint
#    data_type: PointCloud2
#    topic: mobile_base/sensors/bumper_pointcloud
#    marking: true
#    clearing: false
#    min_obstacle_height: 0.0
#    max_obstacle_height: 0.25

inflation_layer:
  enabled:              true
  cost_scaling_factor:  5.0  # exponential rate at which the obstacle cost drops off (default: 10)
  inflation_radius:     0.5  # max. distance from an obstacle at which costs are incurred for planning paths.

static_layer:
  enabled:              false